basicPages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>)/', views.DetailView.as_view(), name='article_detail'),
    path('add/', views.ArticleCreate.as_view(), name='article_add'),
    path('edit/<int:pk>/', views.ArticleUpdate.as_view(), name='article_edit'),
    path('delete/<int:pk>/', views.ArticleDelete.as_view(), name='article_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('basicPages.urls')),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basicPages/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from os.path import join
from config.settings import MEDIA_IMAGES_DIR


def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='Anonyme')[0]


class article(models.Model):
    article_title = models.CharField(max_length=200, verbose_name='Titre')
    article_picture = models.ImageField(
        max_length=500,
        upload_to=join(MEDIA_IMAGES_DIR),
        blank=True,
        null=True,
        verbose_name='Image'
    )
    article_thumbnail = models.ImageField(
        max_length=500,
        upload_to=join(MEDIA_IMAGES_DIR),
        blank=True,
        null=True,
        verbose_name='Miniature'
    )
    article_author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET(get_sentinel_user)
    )
    article_content = models.TextField(verbose_name='Contenu')
    article_pub_date = models.DateTimeField('Date de publication')

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'pk': self.pk})

# TODO: Class comment

basicPages/views.py
from django.views.generic import TemplateView


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'basicPages/home.html'

blog/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import Textarea
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import article


class IndexView(ListView):
    template_name = 'blog/articles.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        article_list = article.objects.order_by('-article_pub_date')
        paginator = Paginator(article_list, 10)  # Show 10 articles per page

        page = self.request.GET.get('page', 1)
        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            articles = paginator.page(1)
        except EmptyPage:
            # If page is out of range, deliver last page of results.
            articles = paginator.page(paginator.num_pages)
        return articles


class DetailView(DetailView):
    model = article
    template_name = 'blog/article.html'


class ArticleCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = article
    template_name_suffix = '_add'
    login_url = '/accounts/login/'
    fields = ['article_title', 'article_picture', 'article_content']
    widgets = {
        'article_content': Textarea(),
    }

    success_message = "L'article a été ajouté avec succès !"

    def get_success_url(self):
        return reverse('blog:article_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.article_pub_date = timezone.now()
        form.instance.article_author = self.request.user
        return super(ArticleCreate, self).form_valid(form)


class ArticleUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    login_url = '/accounts/login/'
    model = article
    template_name_suffix = '_update'
    fields = ['article_title', 'article_picture', 'article_content']
    widgets = {
        'article_content': Textarea(),
    }

    success_message = "L'article a été mis à jour avec succès !"

    def get_success_url(self):
        return reverse('blog:article_detail', kwargs={'pk': self.object.pk})


class ArticleDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    login_url = '/accounts/login/'
    model = article
    success_message = "L'article a été supprimé avec succès !"
    success_url = reverse_lazy('index')

basicPages/templates/basicPages/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>
        Bienvenue !
    </h1>
{% endblock content %}

blog/templates/blog/article.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <h1>
        {{ object.article_title }}
        <span>Le {{ object.article_pub_date }} par {{ object.article_author }}</span>
    </h1>

    {% if user.is_authenticated %}
        <a href="{% url 'blog:article_edit' object.id %}">
            Modifier
        </a>
    {% endif %}
        <div>
            <img class="img-responsive center-block" src="{{ article.article_picture.url }}">
        </div>
    <p>{{ object.article_content|safe }}</p>
{% endblock content %}

blog/templates/blog/article_add.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% block form %}

{% if form.errors %}
    <div>{{ form.errors }}</div>
{% endif %}

<form
    enctype="multipart/form-data"
    name="{{ form.form_name }}"
    method="post"
    action=""
>
	{% csrf_token %}
	{{form.as_p }}
    <button type="submit">
        Publier
    </button>
</form>

{% endblock form %}
{% endblock content %}

blog/templates/blog/article_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% block form %}

{% if form.errors %}
    <div>{{ form.errors }}</div>
{% endif %}

<form
    enctype="multipart/form-data"
    name="{{ form.form_name }}"
    method="post"
    action=""
>
    {% csrf_token %}
    {{form.as_p }}
    <button type="submit">
        Mettre &agrave; jour
    </button>
</form>

{% endblock form %}
{% endblock content %}

blog/templates/blog/articles.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
    <div>
        <a href="{% url 'blog:article_add' %}">
            Nouvel article
        </a>
    </div>
{% endif %}
<hr>
{% if article_list %}
    {% for article in article_list %}
        <div class="row">
            <div>
                <!-- WIP
                    <img class="img-responsive thumbnail" src="{#{ article.article_thumbnail.url }#}">
                -->
            </div>
            <div>
                <h1>
                    <a href="{% url 'blog:article_detail' article.id %}">{{ article.article_title }}</a>
                    <span>Le {{ article.article_pub_date }} par {{ article.article_author }}</span>
                </h1>
                {{ article.article_content|safe|truncatechars_html:500 }}
                <a href="{% url 'blog:article_detail' article.id %}">plus</a>
            </div>
        </div>
        <hr>
    {% endfor %}
{% else %}
    <h1>En cours de construction...</h1>
{% endif %}
{% if article_list.paginator.num_pages > 1 %}
    <nav aria-label="...">
        <ul class="pager">
            {% if article_list.has_previous %}
                <li class="previous">
                    <a href="{% url 'index' %}?page={{ article_list.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span> &nbsp; Articles plus r&eacute;cents
                    </a>
                </li>
            {% endif %}
            {% if article_list.has_next %}
                <li class="next">
                    <a href="{% url 'index' %}?page={{ article_list.next_page_number }}" aria-label="Next">
                        Articles plus ancients &nbsp;<span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Web site template</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>

        <div>
            <div>Web site template</div>
        </div>
        <nav>
            <div>
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div>
                <ul>
                    <li><a href="{% url 'blog:index' %}">Blog</a></li>
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                    <li><a href="#">Page 3</a></li>
                </ul>
            </div>
        </nav>

    <div id="content">
            <div>
                {% block left-panel %} {% endblock left-panel %}
            </div>
            <div>
                {% block content %} {% endblock content %}
            </div>
            <div>
                {% block right-panel %} {% endblock right-panel %}
            </div>
        </div>
        <footer>
            <p>
                Web site by Andy Floch - Free of rights -&nbsp;
                {% if not user.is_authenticated %}
                    <a href="{% url 'login' %}">Login</a>
                {% else %}
                    &nbsp;{{user.get_username }}
                    &nbsp;&nbsp;
                    <a href="{% url 'logout' %}">&nbsp;Deconnexion</a>
                {% endif %}
            </p>
        </footer>
    </body>
</html>